language: perl
perl:
- '5.20'
matrix:
  fast_finish: true
before_install:
- export AUTOMATED_TESTING=1 NONINTERACTIVE_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1 TMPDIR=/tmp
- git clone git://github.com/haarg/perl-travis-helper
- source perl-travis-helper/init
- build-perl
- perl -V
- git config --global user.name "TravisCI"
- git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
- cpanm --quiet --notest --skip-satisfied Dist::Zilla Test::Pod
- dzil authordeps          --missing | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm
  --quiet --notest
- dzil listdeps   --author --missing | grep -vP '[^\w:]' | xargs -n 5 -P 10 cpanm
  --quiet --notest
script:
- dzil smoke --release --author
sudo: false
notifications:
  email: false

